### ISSUE TITLE
Switch panel: the starter switch bindings are run every frame

### ISSUE THREAD

**Issue by coljac** [sparker256/xsaitekpanels#15]
Problem: If I bind a command to a switch such as pitot heat on, it is executed once when I toggle the switch. If I bind a command to, say, mag_off_switch_on_cmd, it's run every frame; I noticed this when my Log.txt reached millions of lines as the aircraft I was using was generating info messages.

Is this behaviour by design?

Example from ini, runs millions of times without switch being touched:

```
Mag Off Switch enable = 2
;command for starter switch off position on command
mag_off_switch_on_cmd = b21/vario_302/mode_te
```
This works as expected, it is executed once when I toggle the switch:
```
Taxi Lights Switch enable = 2
;command for taxi light switch on command
taxi_lights_switch_on_cmd = b21/vario_302/mode_te
```

**Comment by sparker256** [comment]
I think I have this fixed if you could test that would be great. Click on Actions tab then on "Fixed bug in switch panel start switch remapable commands" and download the "Xsaitekpanels_plugin " Artifact. It worked correctly here on Linux but want to be sure before releasing a new version.

**Comment by coljac** [comment]
I tested on Linux and can confirm this is now fixed. Thanks for the very quick patch.

**Comment by sparker256** [comment]
Since this is fixed I will close it.
