### ISSUE TITLE
Archived profiles from 2017 missing lua files

### ISSUE THREAD

**Issue by slgoldberg** [sparker256/xsaitekpanels#8]
I don't see them here in the github project, but last year (I think it was May, 2017) you released a .zip file containing all the legacy profiles and FlyWithLua scripts that you no longer bundle with the plugin (because of the user contributed profiles forum on .org where people can get exactly what they want).

I was looking for a profile that wasn't actually on that forum (from before), and found it in the .zip file archive you published -- no problem.  (It was for the Challenger 300 [XP10 version], which you said you'd added direct support for, but I can't find anything about it anywhere, sorry.)

However, while the xsaitekpanels.ini profile was in the archive, there was no corresponding FlyWithLua script anywhere. Maybe there never was one (?) -- but I know many of the other profiles did have them (and I have most of those, actually).

I double-checked, and the archive has absolutely none of the companion FlyWithLua files that used to be in bundled in the release, and that came/come along with custom profiles for most of the planes either you or others contributed back before you stopped bundling them.

I am guessing whatever tool you used to create the archive either dropped the files (perhaps you had them referenced off a symlink in your local directory you built the archive from?), or you never included them to begin with (by choice, or as an oversight).  Either way, I just wanted to make sure you knew they were missing, in case you have them and are willing to update the .zip file in your .org posting for the archive, so they're preserved for the future.  (If there ever was a FlyWithLua script for the CL300, for example, I would at least like to look at it, knowing the XP11 version that just came out is not that different and I could probably use some or all of what was there; though maybe this is a bad example -- maybe that never was there to begin with).

Anyway -- thanks if you could just consider adding the remaining missing files, or if I'm confused about this for whatever reason. Thanks heaps for all you've done here -- this is an amazingly awesome and powerful tool.

  Steve

**Comment by sparker256** [comment]
Old news
