### ISSUE TITLE
Saitek panels conflict on Linux

### ISSUE THREAD

**Issue by knro** [sparker256/xsaitekpanels#9]
This issue is already covered under the instructions in the XPlane site. However, I had to create a single file to cover all the cases since I had more Saitek devices, so I created 50-saitekpanels.conf to have the following:

```
Section "InputClass"
	Identifier "Saitek Multi"
	MatchProduct "Saitek Pro Flight Multi Panel"
	Option "Ignore" "true"
EndSection

Section "InputClass"
	Identifier "Saitek Radio"
	MatchProduct "Saitek Pro Flight Radio Panel"
	Option "Ignore" "true"
EndSection

Section "InputClass"
	Identifier "Saitek Switch"
	MatchProduct "HOLTEK Saitek Pro Flight Switch Panel"
	Option "Ignore" "true"
EndSection

Section "InputClass"
	Identifier "Saitek Rudder"
	MatchProduct "Saitek Pro Flight Rudder Pedals"
	Option "Ignore" "true"
EndSection

Section "InputClass"
	Identifier "Saitek Quadrant"
	MatchProduct "Saitek Pro Flight Quadrant"
	Option "Ignore" "true"
EndSection
```

EDIT: Ok, it seems the **only** way to get this working is to set "Ignore" to true

**Comment by knro** [comment]
I can confirm that with the above all the mysterious issue with focus and mouse are completely gone!

**Comment by clumsynick** [comment]
Over time Saitek/Logitech has messed around with the "product id". 
I used 
`cat /var/log/Xorg.0.log | grep Saitek` and `cat /var/log/Xorg.0.log | grep Logitech` to figure out the new ids. This is how my conf look like now:

Section "InputClass"
	Identifier "Saitek Multi"
	MatchProduct "Saitek Pro Flight Multi Panel"
	Option "Ignore" "true"
EndSection

Section "InputClass"
	Identifier "Saitek Radio"
	MatchProduct "Logitech Logitech Flight Radio Panel"
	Option "Ignore" "true"
EndSection

Section "InputClass"
	Identifier "Saitek Switch"
	MatchProduct "Intretech Saitek Pro Flight Switch Panel"
	Option "Ignore" "true"
EndSection

Section "InputClass"
	Identifier "Saitek Rudder"
	MatchProduct "Saitek Pro Flight Rudder Pedals"
	Option "Ignore" "true"
EndSection

Section "InputClass"
	Identifier "Saitek Quadrant"
	MatchProduct "Saitek Pro Flight Quadrant"
	Option "Ignore" "true"

EndSection

**Note: I have no Multipanel yet.**

**Comment by sparker256** [comment]
Now fixed
